language: go
sudo: required
go:
- 1.6.4
- 1.7.4
- tip
os:
- linux
- osx
matrix:
  allow_failures:
  - go: tip
  fast_finish: true
install:
- make govendor
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
script:
- make check
- make test-coveralls
- goveralls -coverprofile=coverage.out -service=travis-ci
- go build -race
